apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: bebee
  labels:
    app: file-service
    app.kubernetes.io/name: file-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bebee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        app.kubernetes.io/name: file-service
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: bebee-file-service-sa

      containers:
      - name: file-service
        image: bebee-file-service:latest
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080

        envFrom:
          - secretRef:
              name: file-service-env
