apiVersion: v1
kind: ServiceAccount
metadata:
  name: bebee-file-service-sa
  namespace: bebee
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::383488877070:role/bebee-dev-s3-access-role
  labels:
    app.kubernetes.io/part-of: base
    app.kubernetes.io/component: file-service