apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

labels:
  - pairs:
      app: gateway
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: api-gateway
      app.kubernetes.io/part-of: bebee

resources:
  - deployment.yaml
  - service.yaml