apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: bebee
spec:
  template:
    spec:
      serviceAccountName: payment-service-messaging-sa
      containers:
      - name: payment-service
        volumeMounts:
          - name: config
            mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: payment-service-config
