apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-service-secrets
  namespace: bebee
spec:
  refreshInterval: 5m

  secretStoreRef:
    name: payment-service-sm
    kind: SecretStore

  target:
    name: payment-service-env
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      metadata:
        labels:
          app: payment-service
          environment: dev
      data:
        SERVER_PORT: "8080"
        SPRING_PROFILES_ACTIVE: "dev"
        SPRINGDOC_API_HOST: "https://api.be-bee.link/payment"
        SPRINGDOC_API_DESC: "개발 서버 - PAYMENT 서비스"
        CORS_ALLOWED_ORIGINS: "https://be-bee.link"

  data:
    - secretKey: DB_HOST
      remoteRef: { key: bebee-dev-payment-db-credentials, property: host }
    - secretKey: DB_PORT
      remoteRef: { key: bebee-dev-payment-db-credentials, property: port }
    - secretKey: DB_NAME
      remoteRef: { key: bebee-dev-payment-db-credentials, property: dbname }
    - secretKey: DB_USERNAME
      remoteRef: { key: bebee-dev-payment-db-credentials, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: bebee-dev-payment-db-credentials, property: password }
    - secretKey: TOSS_CLIENT_KEY
      remoteRef: { key: bebee-dev-external-api, property: toss_client_key }
    - secretKey: TOSS_SECRET_KEY
      remoteRef: { key: bebee-dev-external-api, property: toss_secret_key }
