apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    app: member-service
    app.kubernetes.io/name: member-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: member-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
