apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: bebee
spec:
  template:
    spec:
      containers:
        - name: notification-service
          env:
            - name: FIREBASE_SERVICE_ACCOUNT_KEY_PATH
              value: /app/secrets/firebase-service-account.json
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: firebase-key-volume
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: notification-service-config
        - name: firebase-key-volume
          secret:
            secretName: notification-secrets
            items:
              - key: firebase-service-account.json
                path: firebase-service-account.json
