apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: notification-secrets
    creationPolicy: Owner
  data:
    - secretKey: KAKAO_API_KEY
      remoteRef:
        key: bebee-dev-external-api
        property: kakao_api_key
    - secretKey: firebase-service-account.json
      remoteRef:
        key: bebee-dev-external-api
        property: firebase_service_account_key
