apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

resources:
  - ../../base
  - secret-manager-sa.yaml
  - messaging-sa.yaml
  - secret-store.yaml
  - external-secret.yaml

labels:
- pairs:
    environment: dev

configMapGenerator:
  - name: notification-service-config
    files:
      - application.yaml=application-dev.yaml

images:
  - name: bebee-notification-service
    newName: 383488877070.dkr.ecr.ap-northeast-2.amazonaws.com/bebee-notification-service
    newTag: c27c2fa58135ff5b0e00dcd45b12ef95a08aa12f

patches:
  - path: deployment-patch.yaml
