apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-secrets-sa
  namespace: bebee
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::383488877070:role/bebee-dev-secrets-manager-access-role
  labels:
    app: notification-service
    environment: dev
    component: external-secrets
