apiVersion: v1
kind: Service
metadata:
  name: match-service
  labels:
    app: match-service
    app.kubernetes.io/name: match-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: match-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
