apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: notification-service-sm
  namespace: bebee
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: notification-service-secrets-sa
