apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

resources:
  - ../../base

labels:
  - pairs:
      environment: dev

images:
  - name: bebee-ocr-service
    newName: 383488877070.dkr.ecr.ap-northeast-2.amazonaws.com/bebee-ocr-service
    newTag: latest
