apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: bebee
  labels:
    app: chat-service
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bebee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
        app.kubernetes.io/name: chat-service
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: chat-service
        image: bebee-chat-service:latest

        ports:
        - containerPort: 8080
          name: http

        envFrom:
          - secretRef:
              name: chat-service-env

        livenessProbe:
          httpGet:
            path: /chat/actuator/health
            port: 8080
          initialDelaySeconds: 20
