apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: file-service-sm
  namespace: bebee
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      # IRSA (IAM Roles for Service Accounts)를 통한 인증
      auth:
        jwt:
          serviceAccountRef:
            name: file-service-secrets-sa