apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: bebee
spec:
  template:
    spec:
      serviceAccountName: chat-service-account-sa
      containers:
      - name: chat-service
        volumeMounts:
          - name: config
            mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: chat-service-config
