apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat-service-secrets
  namespace: bebee
spec:
  # 5분마다 Secrets Manager에서 값을 동기화
  refreshInterval: 5m

  # SecretStore 참조
  secretStoreRef:
    name: chat-service-sm
    kind: SecretStore

  # 생성될 Kubernetes Secret 이름
  target:
    name: chat-service-env
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      metadata:
        labels:
          app: chat-service
          environment: dev
      data:
        SERVER_PORT: "8080"
        SPRING_PROFILES_ACTIVE: "dev"
        SPRINGDOC_API_HOST: "https://api.be-bee.link/chat"
        SPRINGDOC_API_DESC: "개발 서버 - CHAT 서비스"
        CORS_ALLOWED_ORIGINS: "https://be-bee.link"

  # AWS Secrets Manager에서 가져올 데이터
  data:
    - secretKey: DB_HOST
      remoteRef: { key: bebee-dev-chat-db-credentials, property: host }
    - secretKey: DB_PORT
      remoteRef: { key: bebee-dev-chat-db-credentials, property: port }
    - secretKey: DB_NAME
      remoteRef: { key: bebee-dev-chat-db-credentials, property: dbname }
    - secretKey: DB_USERNAME
      remoteRef: { key: bebee-dev-chat-db-credentials, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: bebee-dev-chat-db-credentials, property: password }
    - secretKey: REDIS_HOST
      remoteRef: { key: bebee-dev-redis-credentials, property: primary_endpoint }
    - secretKey: REDIS_PORT
      remoteRef: { key: bebee-dev-redis-credentials, property: port }
    - secretKey: MONGODB_USERNAME
      remoteRef: { key: bebee-dev-mongodb-credentials, property: username }
    - secretKey: MONGODB_PASSWORD
      remoteRef: { key: bebee-dev-mongodb-credentials, property: password }
    - secretKey: MONGODB_HOST
      remoteRef: { key: bebee-dev-mongodb-credentials, property: host }
    - secretKey: MONGODB_URI
      remoteRef: { key: bebee-dev-mongodb-credentials, property: uri }
