apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

resources:
  - ../../base
  - secret-manager-sa.yaml
  - messaging-sa.yaml
  - secret-store.yaml
  - external-secret.yaml

labels:
- pairs:
    environment: dev

configMapGenerator:
  - name: chat-service-config
    files:
      - application.yaml=application-dev.yaml

images:
  - name: bebee-chat-service
    newName: 383488877070.dkr.ecr.ap-northeast-2.amazonaws.com/bebee-chat-service
    newTag: 22d5ca6ab0ba409bf59002953c96fc9ff1682b97

patches:
  - path: deployment-patch.yaml
