apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger
  namespace: bebee
  labels:
    app: swagger
    app.kubernetes.io/name: swagger
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bebee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
        - name: swagger
          image: bebee-swagger-service:latest
          ports:
            - containerPort: 8080
              name: http

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
