apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: bebee
  labels:
    app: swagger
    app.kubernetes.io/name: swagger
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bebee
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: swagger
