apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: member-service-secrets
  namespace: bebee
spec:
  # 5분마다 Secrets Manager에서 값을 동기화
  refreshInterval: 5m

  # SecretStore 참조
  secretStoreRef:
    name: member-service-sm
    kind: SecretStore

  # 생성될 Kubernetes Secret 이름
  target:
    name: member-service-env
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      metadata:
        labels:
          app: member-service
          environment: dev
      data:
        SERVER_PORT: "8080"
        SPRING_PROFILES_ACTIVE: "dev"
        SPRINGDOC_API_HOST: "https://api.be-bee.link/member"
        SPRINGDOC_API_DESC: "개발 서버 - Member 서비스"
        CORS_ALLOWED_ORIGINS: "https://be-bee.link"
        OCR_BASE_URL:  "http://ocr-service"

  # AWS Secrets Manager에서 가져올 데이터
  data:
    - secretKey: DB_HOST
      remoteRef: { key: bebee-dev-member-db-credentials, property: host }
    - secretKey: DB_PORT
      remoteRef: { key: bebee-dev-member-db-credentials, property: port }
    - secretKey: DB_NAME
      remoteRef: { key: bebee-dev-member-db-credentials, property: dbname }
    - secretKey: DB_USERNAME
      remoteRef: { key: bebee-dev-member-db-credentials, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: bebee-dev-member-db-credentials, property: password }
    - secretKey: REDIS_HOST
      remoteRef: { key: bebee-dev-redis-credentials, property: primary_endpoint }
    - secretKey: REDIS_PORT
      remoteRef: { key: bebee-dev-redis-credentials, property: port }
    - secretKey: JWT_SECRET
      remoteRef: { key: bebee-dev-jwt-secret, property: jwt_secret }
    - secretKey: JWT_ISSUER
      remoteRef: { key: bebee-dev-jwt-secret, property: issuer }
    - secretKey: JWT_ACCESS_TOKEN_EXPIRES_IN
      remoteRef: { key: bebee-dev-jwt-secret, property: access_token_expires_in }
    - secretKey: JWT_REFRESH_TOKEN_EXPIRES_IN
      remoteRef: { key: bebee-dev-jwt-secret, property: refresh_token_expires_in }