apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  namespace: bebee
  labels:
    app: match-service
    app.kubernetes.io/name: match-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: bebee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
        app.kubernetes.io/name: match-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: match-service
          image: bebee-match-service:latest
          
          ports:
            - containerPort: 8080
              name: http
          
          envFrom:
            - secretRef:
                name: match-service-env
