apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

resources:
  - ../../common
  - deployment.yaml
  - service.yaml

# 공통 레이블
labels:
  - includeSelectors: true
    pairs:
      app: chat-service
      app.kubernetes.io/name: file-service
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: bebee
