apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: file-service-secrets
  namespace: bebee
spec:
  # 5분마다 Secrets Manager에서 값을 동기화
  refreshInterval: 5m

  # SecretStore 참조
  secretStoreRef:
    name: file-service-sm
    kind: SecretStore

  # 생성될 Kubernetes Secret 이름
  target:
    name: file-service-env
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      metadata:
        labels:
          app: file-service
          environment: dev
      data:
        SERVER_PORT: "8080"
        SPRING_PROFILES_ACTIVE: "dev"
        SPRINGDOC_API_HOST: "https://api.be-bee.link/file"
        SPRINGDOC_API_DESC: "개발 서버 - FILE 서비스"
        CORS_ALLOWED_ORIGINS: "https://be-bee.link"

  # AWS Secrets Manager에서 가져올 데이터
  data:
    - secretKey: AWS_REGION
      remoteRef: { key: bebee-dev-aws-config, property: region}

    - secretKey: AWS_S3_BUCKET
      remoteRef: { key: bebee-dev-s3-images, property: bucket_name}
