apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

resources:
  - ../../base
  - s3-sa.yaml
  - secret-manager-sa.yaml
  - secret-store.yaml
  - external-secret.yaml

labels:
- pairs:
    environment: dev

configMapGenerator:
  - name: file-service-config
    files:
      - application.yaml=application-dev.yaml

images:
  - name: bebee-file-service
    newName: 383488877070.dkr.ecr.ap-northeast-2.amazonaws.com/bebee-file-service
    newTag: 427be485958916e1d4c29973b741ae7a166d60c5

patches:
  - path: deployment-patch.yaml
