apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bebee

commonLabels:
  app: chat-service
  app.kubernetes.io/name: chat-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: bebee

resources:
  - deployment.yaml
  - service.yaml
