apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: member-service-secrets
  namespace: bebee
spec:
  refreshInterval: 5m

  secretStoreRef:
    name: member-service-sm
    kind: SecretStore

  target:
    name: member-service-env
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      metadata:
        labels:
          app: member-service
          environment: dev
      data:
        SERVER_PORT: "8080"
        SPRING_PROFILES_ACTIVE: "dev"

  data:
    - secretKey: DB_HOST
      remoteRef: { key: bebee-dev-member-db-credentials, property: host }
    - secretKey: DB_PORT
      remoteRef: { key: bebee-dev-member-db-credentials, property: port }
    - secretKey: DB_NAME
      remoteRef: { key: bebee-dev-member-db-credentials, property: dbname }
    - secretKey: DB_USERNAME
      remoteRef: { key: bebee-dev-member-db-credentials, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: bebee-dev-member-db-credentials, property: password }
